#!/usr/bin/env node

var cli = require('cli').enable('status'); //Enable 2 plugins

cli.parse({
    test:   ['t', 'testing'],
    port:  ['p', 'Listen on this port', 'number', 8080]
});

cli.main(function(args, options) {
    
    console.log(args);

    //this.debug('Testing 1 ' + options.test);

    this.ok('Testing 2 ' + options.port);
});